{
 "title": "Battery Saver dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Статус реле",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"battery_saver_logs\",charger_status=~\".+\"}"
    }
   ]
  },
  {
   "title": "Процент заряда АКБ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"battery_saver_logs\", battery_percentage=~\".+\"}"
    }
   ]
  },
  {
   "title": "Логи",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"battery_saver_logs\"}"
    }
   ]
  }
 ]
}